# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import django_renderservice.render_service_pb2 as render__service__pb2


class RenderServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.Render = channel.unary_unary(
            "/render_service.RenderService/Render",
            request_serializer=render__service__pb2.RenderRequest.SerializeToString,
            response_deserializer=render__service__pb2.RenderResponse.FromString,
        )


class RenderServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Render(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Render": grpc.unary_unary_rpc_method_handler(
            servicer.Render,
            request_deserializer=render__service__pb2.RenderRequest.FromString,
            response_serializer=render__service__pb2.RenderResponse.SerializeToString,
        )
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "render_service.RenderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
